---
    - name: Yum install dependences in REL system
      yum: name=make,gcc,gcc-c++,kernel-devel,git,autoconf,automake,libtool,subversion,pkgconfig,java-1.6.0-openjdk-devel state=latest update_cache=yes

    - name: Yum install openmpi in REL system
      yum: name=openmpi,openmpi-devel state=latest

    - name: update PATH environment variable
      shell: export PATH=$PATH:/usr/lib/openmpi/bin
